refresh_rate: 30 seconds
appenders:
  stdout-appender:
    kind: console
  file-appender:
    kind: file
    path: "log/ppaass-agent.log"
    encoder:
      pattern: "{d} - {l} - {f}:{L}:{I} - {m}{n}"
root:
  level: debug
  appenders:
    - file-appender
    - stdout-appender
loggers:
  main:
    level: debug
    appenders:
      - file-appender
      - stdout-appender
    additive: true